### ISSUE TITLE
No file: /spec/schema.lua

### ISSUE THREAD

**Issue by makorne** [vladfaust/tarantool-crystal#8]
`Connect to tarantool via console (docker exec -i -t mytarantool console) and apply schema found in /spec/schema.lua`

```
/opt/tarantool # ls /spec/schema.lua
ls: /spec/schema.lua: No such file or directory
```

**Comment by vladfaust** [comment]
Oh, yes, it's in https://github.com/vladfaust/tarantool-crystal/blob/master/spec/helpers.lua now. I forgot to update README, sorry for that.

**Comment by vladfaust** [comment]
Ah, no. You're trying to apply schema from within a Docker container, but you should instead take the contents of file found at https://github.com/vladfaust/tarantool-crystal/blob/master/spec/helpers.lua and apply it to Tarantool (basically just ctrl-c ctrl-v).
