### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by makorne** [vladfaust/tarantool-crystal#9]
```
shards install
Fetching https://github.com/vladfaust/tarantool-crystal.git
Error resolving tarantool (~> 0.1.0)
```
Others github dependencies install without problems.

**Comment by vladfaust** [comment]
Thanks for the heads up! The issue is that there is no tag released yet 😅 But I recently got a note from my backer, that the shard is working really good now, so I'm about to finally release 0.1.0. Thanks!

**Comment by vladfaust** [comment]
Fixed! See https://github.com/vladfaust/tarantool.cr/releases
